name: Build the project
on:
  push:
jobs:
  build:
    name: Test context
    runs-on: ubuntu-latest
    container:
      image: node:18
      env:
        NODE_ENV: development
#      volumes:
#        - my_docker_volume:/volume_mount
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test
        env:
          CI: true
      - name: Build
        run: npm run build
      - name: Save Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: p-n-t-build
          path: build
