name: Build the project
on:
  push:
jobs:
  build:
    name: Test context
    runs-on: ubuntu-latest
    steps:
      - name: Display event name
        run: npm i
      - name: Display event name
        run: npm build
