name: Build the project
on:
  push:
jobs:
  build:
    name: Test context
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm build
