name: Build the project
on:
  push:
jobs:
  build:
    name: Test context
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test
        env:
          CI: true
      - name: Build
        run: npm run build
      - name: Save Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: p-n-t-build
          path: build
