name: pnt-ui

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
  deploy:
    needs: build
    if: >
      success() &&
       github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -m 700 ~/.ssh/
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      - name: Call script
        run: ssh $SERVER_USER@$SERVER_NAME "./update.sh"
        env:
          SERVER_USER: ${{secrets.SERVER_USER}}
          SERVER_NAME: ${{secrets.SERVER_NAME}}
